" File ~/.vimrc
" ($HOME/_vimrc on Windows)
" cp vimrc ~/.vimrc

" enable file type detection
filetype on

" for Linux distros that disable filetype detection
filetype plugin on

" for all set column width
highlight OverLength ctermbg=darkred ctermfg=white guibg=#FFD9D9 guifg=white
set colorcolumn=80
